
### Create new user account
POST http://localhost:8080/user-account
Content-Type: application/json

{
  "firstName": "John2",
  "lastName": "Doe2",
  "initialBalance" : 10.00
}

### Get user account details
GET http://localhost:8080/user-account/2


### Create new bank account
POST http://localhost:8080/user-account/1/bank-account
Content-Type: application/json

{
  "initialBalance": 20.00,
  "currency": "USD"
}

### Get bank account
GET http://localhost:8080/user-account/1/bank-account/3

### Get bank account
GET http://localhost:8080/user-account/1/bank-account/1/balance
### Get bank account
GET http://localhost:8080/user-account/1/bank-account/2/balance

### Create new operation
POST http://localhost:8080/user-account/1/operation
Content-Type: application/json

{
  "currency": "USD",
  "action": "BUY",
  "value": 10
}

### Get operations list for bank account
GET http://localhost:8080/user-account/1/bank-account/1/operation
